export const FETCH_USER_INFO = "FETCH_USER_INFO";

export const OPEN_SIDEBAR = "TOGGLE_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const OPEN_GENERATOR_FORM = "OPEN_GENERATOR_FORM";
